// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Spec TestHelpers
//
// Command:
// $ goagen
// --design=github.com/aep-dev/terraform-provider-openapi/v3/examples/goa/api/design
// --out=$(GOPATH)/src/github.com/aep-dev/terraform-provider-openapi/v3/examples/goa/api
// --version=v1.3.1

package test
